### ISSUE TITLE
Use alpine or smaller images for workshop 

### ISSUE THREAD

**Issue by cloudyuga** [container-workbook/docker-workshop#7]
Instead of using larger images, I would recommend use smaller images for the demo/workshop like alpine. 

```
$ docker pull centos
$ docker pull fedora:24
$ docker pull debian
$ docker pull centos/postgresql-94-centos7
```

We don't live in perfect where everyone would have done pre-requisite before the workshop.. or have infinite network bandwidth in conferences :).

**Comment by LalatenduMohanty** [comment]
@cloudyuga Removed the section you mentioned as it was redundant and added alpine in https://github.com/container-workbook/docker-workshop#122-pull-an-image

**Comment by LalatenduMohanty** [comment]
@surajssd do we need centos/postgresql-94-centos7 for the demo application?

**Comment by surajssd** [comment]
> @surajssd do we need centos/postgresql-94-centos7 for the demo application?

@LalatenduMohanty nope.

We might need `redis` image though!
